<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Análisis Estadístico Básico con R C5-S1</title>

<script src="site_libs/header-attrs-2.7/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">R Lationamérica - RLab</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Inicio</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Prácticas
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="PractCasa01-full.html">Práctica de Casa 1: Programación Básica con R</a>
    </li>
    <li>
      <a href="PractCasa02-full.html">Práctica de Casa 2: Programación con R y dplyr</a>
    </li>
    <li>
      <a href="PractCasa03-full.html">Práctica de Casa 3: Análisis Estadístico Básico</a>
    </li>
    <li>
      <a href="PractCasa04-full.html">Práctica de Casa 4: Gráficos Avanzados con ggplot2</a>
    </li>
    <li>
      <a href="PractCasa05-full.html">Práctica de Casa 5: Modelos Lineales de Efectos Mixtos (LMM)</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Análisis Estadístico Básico con R C5-S1</h1>

</div>


<div id="práctica-de-casa-05---modelos-lineales-de-efectos-mixtos-lmm" class="section level1">
<h1><strong>Práctica de Casa 05 - Modelos Lineales de Efectos Mixtos (LMM)</strong></h1>
<p>Link de la práctica desarrollada: <a href="https://irwingss.github.io/IrwingRLab/PractCasa05-full.html">Práctica de Casa 05 - Gráficos Avanzados con ggplot2 (irwingss.github.io)</a></p>
<p>Realiza los siguientes ejercicios durante tu tiempo libre para reforzar practicar las funciones adicionales y geoms que aprendiste durante la semana 12 del programa (Curso 5).</p>
<p>Recuerda realizar esta práctica luego de haber desarrollado:</p>
<ul>
<li>R-Notebook-C5-S1.Rmd</li>
</ul>
<p><strong>En clase realizamos los gráficos y resultados para el caso donde la variable X es numérica. Estos dos ejercicios te proveerán de la práctica necesaria para problemas de investigación donde la variable explicativa no es numérica sino categórica.</strong></p>
<blockquote>
<p><strong>Nota 1:</strong> Si necesitas crear un code chunk los atajos en el teclado son en WINDOWS: <code>Crtl+Alt+i</code>, y en MAC: <code>Command+Alt+i</code>.</p>
</blockquote>
<p><strong>Activa las librarías a usar</strong></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MuMIn)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmTMB)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AICcmodavg)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span></code></pre></div>
</div>
<div id="ejercicio-1" class="section level1">
<h1><strong>Ejercicio 1:</strong></h1>
<p>Carga la base de datos <code>oats</code> de la librería <code>MASS</code>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carga la base de datos oats de la libreria MASS</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:patchwork&#39;:
## 
##     area</code></pre>
<pre><code>## The following object is masked from &#39;package:rstatix&#39;:
## 
##     select</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;oats&quot;</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Usa la función head para ver las seis primeras filas del data frame</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(oats)</span></code></pre></div>
<pre><code>##   B           V      N   Y
## 1 I     Victory 0.0cwt 111
## 2 I     Victory 0.2cwt 130
## 3 I     Victory 0.4cwt 157
## 4 I     Victory 0.6cwt 174
## 5 I Golden.rain 0.0cwt 117
## 6 I Golden.rain 0.2cwt 114</code></pre>
<p>Las variables de esta base de datos son las siguiente:</p>
<ul>
<li><p>Y: rendimiento de la producción en toneladas por acre.</p></li>
<li><p>N: Tratamiento de nitrógeno (estiércol, 3 niveles), 0.0cwt, 0.2cwt, 0.4cwt y 0.6cwt.</p></li>
<li><p>V: Variedad de avena (3 niveles), Victory, Golden.rain y Marvellous.</p></li>
<li><p>B: Bloques, niveles I, II, III, IV, V y VI.</p></li>
</ul>
<p>El objetivo de este ejercicio es encontrar la relación que existe entre el uso de diferentes niveles de nitrógeno y diferentes variedades de avena en el rendimiento final de las parcelas de estudio (producción por acre). Se determinó un estudio por bloques ya que la zona es irregular y las micro-características de cada bloque podrían influenciar en ligeras variaciones en la producción. Se desea remover este efecto aleatorio y quedarse con la explicación de N y V sobre la variable respuesta Y.</p>
<div id="realiza-la-exploración-previa-de-la-base-de-datos" class="section level4">
<h4><strong>1) Realiza la exploración previa de la base de datos</strong></h4>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ver normalidad de la variable respuesta</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>nortest<span class="sc">::</span><span class="fu">ad.test</span>(oats<span class="sc">$</span>Y)</span></code></pre></div>
<pre><code>## 
##  Anderson-Darling normality test
## 
## data:  oats$Y
## A = 0.23768, p-value = 0.7759</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ver Posible efecto aleatorio (experimentar con N*V)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> N, <span class="at">data =</span> oats)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>resid <span class="ot">&lt;-</span> <span class="fu">residuals</span>(lm)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(resid <span class="sc">~</span> oats<span class="sc">$</span>B)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">0</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="PractCasa05-full_files/figure-html/unnamed-chunk-3-1.png" /><!-- --></p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(resid <span class="sc">~</span> oats<span class="sc">$</span>V)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">0</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="PractCasa05-full_files/figure-html/unnamed-chunk-3-2.png" /><!-- --></p>
</div>
<div id="crea-los-modelos-y-realiza-la-selección-del-mejor-modelo" class="section level4">
<h4><strong>2) Crea los modelos y realiza la selección del mejor modelo</strong></h4>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo lineal (nómbralo ModV) explicado solo por la variedad (V).</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>ModV <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> V, <span class="at">data=</span>oats)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo lineal (nómbralo ModN) explicado solo por el nitrógeno (N).</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>ModN <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> N, <span class="at">data=</span>oats)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo lineal (nómbralo ModVN) explicado solo por la interacción entre N y V. </span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Una interacción la colocarás como la multiplicación entre las variables: N*V.</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>ModVN <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> V<span class="sc">*</span>N, <span class="at">data=</span>oats)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co"># LMM (nómbralo Mod1) explicado por la variedad (V), y controlando por </span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="co"># bloques (B) como interceptos aleatorio. </span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>Mod1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Y <span class="sc">~</span> V <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>B), <span class="at">data=</span>oats, <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="co"># LMM (nómbralo Mod2) explicado por el nitrógeno (N), y controlando por </span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="co"># bloques (B) como interceptos aleatorio. </span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>Mod2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Y <span class="sc">~</span> N <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>B), <span class="at">data=</span>oats, <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="co"># LMM (nómbralo Mod3) explicado la interacción N*V, y controlando por </span></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="co"># bloques (B) como interceptos aleatorio. </span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>Mod3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Y <span class="sc">~</span> V<span class="sc">*</span>N <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>B), <span class="at">data=</span>oats, <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Copia los modelos Mod1 al Mo3, cámbiales los nombres por Mod4, Mod5, y Mod6, </span></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="co"># y esta vez define los interceptos aleatorios como un anidamiento de </span></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Variedad dentro de Bloque (B/V). </span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>Mod4 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Y <span class="sc">~</span> V <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>B<span class="sc">/</span>V), <span class="at">data=</span>oats, <span class="at">REML=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## boundary (singular) fit: see ?isSingular</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>Mod5 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Y <span class="sc">~</span> N <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>B<span class="sc">/</span>V), <span class="at">data=</span>oats, <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>Mod6 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Y <span class="sc">~</span> V<span class="sc">*</span>N <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>B<span class="sc">/</span>V), <span class="at">data=</span>oats, <span class="at">REML=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<p>En la selección de modelos, este código para revisar el criterio de información (sea AIC, AICc o BIC) es mucho más cómodo y corto. La función <code>lst()</code> de la librería <code>tibble</code> permite realizar una lista y automáticamente nombrar cada elemento con el nombre del objeto. Algo que la función típica <code>list()</code> no hace. Esta lista contiene los propios modelos (no solo sus nombres), por lo que les podemos aplicar, por ejemplo, el cálculo del AICc, con la función <code>lapply()</code> que permite aplicar <strong>una función</strong> a una <strong>lista</strong>. Prueba cambiando la función aplicada sobre la lista por AIC, BIC, o calcula los coeficientes de cada elemento con coef(), revisa el resumen de cada elemento con summary().</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selección de modelos</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>Lista <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">lst</span>(ModV, ModN, ModVN, Mod1, Mod2, Mod3, Mod4, Mod5, Mod6)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(Lista, AICc)</span></code></pre></div>
<pre><code>## $ModV
## [1] 684.3151
## 
## $ModN
## [1] 654.1299
## 
## $ModVN
## [1] 670.5844
## 
## $Mod1
## [1] 675.2818
## 
## $Mod2
## [1] 627.6604
## 
## $Mod3
## [1] 640.4679
## 
## $Mod4
## [1] 677.665
## 
## $Mod5
## [1] 616.9145
## 
## $Mod6
## [1] 634.4771</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Si pasamos la lista de AICc con un pipe por la función %&gt;% sapply(cbind) </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># obtendremos un vector con los elementos nombrados. </span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Esto lo pasamos a su vez por la función sort() para que se reordenen.</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(Lista, AICc) <span class="sc">%&gt;%</span> <span class="fu">sapply</span>(cbind) <span class="sc">%&gt;%</span> <span class="fu">sort</span>()</span></code></pre></div>
<pre><code>##     Mod5     Mod2     Mod6     Mod3     ModN    ModVN     Mod1     Mod4 
## 616.9145 627.6604 634.4771 640.4679 654.1299 670.5844 675.2818 677.6650 
##     ModV 
## 684.3151</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplica la función r.squaredLR para calcular el R cuadrado ajustado por </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># el método de Likelihood Ratio Test. Este test me da un resultado comparable </span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># con el R2 de un modelo lineal clásico. Recuerda que me indica la fuerza de la</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># relación entre Y y la parte sistemática de la ecuación (es decir, las </span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># variables X). Esto se interpreta también como la cantidad de varianza que </span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># las variables X explican de Y. Aquí la función sort() nos daría </span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># el resultado comenzando con el valor más bajo, pero queremos saber cuál </span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># es el más alto, por lo que en su lugar usaremos rev().</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(Lista, r.squaredLR) <span class="sc">%&gt;%</span> <span class="fu">sapply</span>(cbind) <span class="sc">%&gt;%</span> <span class="fu">rev</span>()</span></code></pre></div>
<pre><code>##       Mod6       Mod5       Mod4       Mod3       Mod2       Mod1      ModVN 
## 0.68128923 0.65714005 0.17513970 0.63788024 0.58813083 0.17513970 0.42566527 
##       ModN       ModV 
## 0.38511371 0.03436239</code></pre>
<p>En este punto tenemos que por AIC, los mejores modelos son Mod5, Mod2 y Mod6, y que estos modelos tienen buenos R2 ajustado por LR: 0.66, 0.59, 0.68 respectivamrnte. La decisión la debes basar en el AIC. Revisa si existen diferencias significativas entre los modelos y escoge - Si existen diferencias significativas, el que tenga menor AIC. - Si no existen diferencias significativas, el que tenga la menor cantidad de parámetros (npar). - Y si todo está idéntico entre los modelos, es decir, no hay diferencias significativas y no hay diferencia en el número de parámetros, puedes escoger o el más sencillo (con fórmula más simple) o el que tiene mejor RsquaredLR.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(Mod5, Mod2) </span></code></pre></div>
<pre><code>## Data: oats
## Models:
## Mod2: Y ~ N + (1 | B)
## Mod5: Y ~ N + (1 | B/V)
##      npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)    
## Mod2    6 626.37 640.03 -307.18   614.37                         
## Mod5    7 615.16 631.10 -300.58   601.16 13.204  1  0.0002794 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># existen diferencias sig. Gana Mod5</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(Mod5, Mod6) </span></code></pre></div>
<pre><code>## Data: oats
## Models:
## Mod5: Y ~ N + (1 | B/V)
## Mod6: Y ~ V * N + (1 | B/V)
##      npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
## Mod5    7 615.16 631.10 -300.58   601.16                     
## Mod6   15 625.91 660.06 -297.95   595.91 5.2587  8     0.7296</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># no existen diferencias sig. Gana Mod5 por menor npar</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(Mod2, Mod6) </span></code></pre></div>
<pre><code>## Data: oats
## Models:
## Mod2: Y ~ N + (1 | B)
## Mod6: Y ~ V * N + (1 | B/V)
##      npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)  
## Mod2    6 626.37 640.03 -307.18   614.37                       
## Mod6   15 625.91 660.06 -297.95   595.91 18.462  9    0.03017 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># existen diferencias sig. Gana Mod2, pero este no es mejor que mod5</span></span></code></pre></div>
</div>
<div id="crea-el-modelo-final-e-interpreta-los-resultados" class="section level4">
<h4><strong>3) Crea el modelo final e interpreta los resultados</strong></h4>
<p>Nos quedamos con Mod5. Continua el ejercicio para obtener el modelo final: Y siendo explicado por N y retirando el efecto aleatorio de bloques y variedades.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Guarda el modelo Final (nómbralo final) con REML verdadero</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>final <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Y <span class="sc">~</span> N <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>B<span class="sc">/</span>V), <span class="at">data=</span>oats, <span class="at">REML=</span><span class="cn">TRUE</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ahora, los gráficos de Gusano (Caterpilar Plot) de los efectos aleatorios </span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># que vimos en clase es mejor obtenerlos con la función descrita a continuación</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>cater <span class="ot">&lt;-</span> <span class="fu">dotplot</span>(<span class="fu">ranef</span>(final, <span class="at">condVar=</span><span class="cn">TRUE</span>), <span class="at">strip=</span><span class="cn">FALSE</span>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualiza el efecto de los bloques con su nombre B</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>cater<span class="sc">$</span>B</span></code></pre></div>
<p><img src="PractCasa05-full_files/figure-html/unnamed-chunk-7-1.png" /><!-- --></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualiza el efecto de las variedades anidadas en los bloques con </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># su nombre `V:B`</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>cater<span class="sc">$</span><span class="st">`</span><span class="at">V:B</span><span class="st">`</span></span></code></pre></div>
<p><img src="PractCasa05-full_files/figure-html/unnamed-chunk-7-2.png" /><!-- --></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtén los CI Automáticos para que veas si los intervalos de confianza </span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># incluyen o no a 0 y sepas si es que los coeficientes de las categorías </span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># de N son significativos.</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>final <span class="sc">%&gt;%</span> <span class="fu">tidy</span>(<span class="at">conf.int=</span><span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="fu">View</span>()</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Revisa los resultados del modelo. Recuerda que nos interesa interpretar </span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co"># los efectos fijos del modelo. Estos se leen como en una regresión </span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># lineal cualquiera.</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(final)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: Y ~ N + (1 | B/V)
##    Data: oats
## 
## REML criterion at convergence: 582.2
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.78156 -0.61169  0.02222  0.62201  1.68138 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  V:B      (Intercept) 121.9    11.04   
##  B        (Intercept) 210.4    14.51   
##  Residual             162.6    12.75   
## Number of obs: 72, groups:  V:B, 18; B, 6
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   79.389      7.132  11.131
## N0.2cwt       19.500      4.250   4.588
## N0.4cwt       34.833      4.250   8.196
## N0.6cwt       44.000      4.250  10.353
## 
## Correlation of Fixed Effects:
##         (Intr) N0.2cw N0.4cw
## N0.2cwt -0.298              
## N0.4cwt -0.298  0.500       
## N0.6cwt -0.298  0.500  0.500</code></pre>
<p><strong>Interpretación:</strong> el modelo LMM indica que si existe un efecto aleatorio de bloque y de variedad anidada dentro de bloques (como indican los caterpilar plots) y la cantidad de varianza explicada por estas variables de efecto aleatorio revisado en el summary del modelo. Por su parte, la interpretación de los efectos fijos (todos ellos significativos dado que los CI no incluyen al cero) nos indica que el mejor rendimiento se genera por N0.6cwt, con un incremento de 44 unidades sobre el promedio del nivel base (el cual en este caso es N0cwt, es decir, no aplicación de nitrógeno). En general aplicando N0.6cwt puedo producir un promedio de 44.000 + 79.389 = 123.389 toneladas por acre.</p>
</div>
<div id="genera-el-gráfico-final" class="section level4">
<h4><strong>4) Genera el gráfico final</strong></h4>
<p>El gráfico de efectos fijos, o predictivo, lo podemos generar rápidamente con la función <code>plot_model()</code> de la librería <code>sjPlot</code>.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(final, <span class="at">type=</span><span class="st">&quot;eff&quot;</span>)</span></code></pre></div>
<pre><code>## $N</code></pre>
<p><img src="PractCasa05-full_files/figure-html/unnamed-chunk-8-1.png" /><!-- --></p>
<p>No obstante, la versión en ggplot2, más elaborada, requiere de obtener la información de los coeficiente e intervalos de confianza para crear las barras de error de cada coeficiente para cada nivel de Nitrógeno.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera el modelo final donde el intercepto (nivel báse de la variable N, </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># que es la misma categoría 0.0cwt) se muestre como nivel y no como intercepto. </span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Esto se logra colocando un número 0 antes de la variable X en la fórmula.</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>final.para.grafico<span class="ot">&lt;-</span> <span class="fu">lmer</span>(Y <span class="sc">~</span> <span class="dv">0</span><span class="sc">+</span>N <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>B<span class="sc">/</span>V), <span class="at">data=</span>oats, <span class="at">REML=</span><span class="cn">TRUE</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener los coeficientes para ambos efectos aleatorios B y V anidado en B</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>coef.B <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(broom.mixed<span class="sc">::</span><span class="fu">tidy</span>(final.para.grafico, <span class="at">conf.int=</span><span class="cn">TRUE</span>))[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,]</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>coef.B<span class="sc">$</span>term <span class="ot">&lt;-</span> <span class="fu">unique</span>(oats<span class="sc">$</span>N)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Generar el gráfico</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data=</span>oats, <span class="fu">aes</span>(<span class="at">x=</span>N, <span class="at">y=</span>Y, <span class="at">color=</span>V, <span class="at">shape=</span>B), <span class="at">width=</span><span class="fl">0.15</span>)<span class="sc">+</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>coef.B, <span class="fu">aes</span>(<span class="at">x=</span>term, <span class="at">y=</span>estimate), <span class="at">shape=</span><span class="dv">15</span>)<span class="sc">+</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data=</span>coef.B, <span class="fu">aes</span>(<span class="at">x=</span>term, <span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high), </span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;LMM de la Producción en T/acre de avena </span><span class="sc">\n</span><span class="st">con diferentes concentraciones de nitrógeno&quot;</span>, </span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle=</span><span class="st">&quot;Modelo con efectos aleatorios definidos por Variedad de Avena y por Bloque&quot;</span>,  </span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">&quot;Concetración de N&quot;</span>, <span class="at">y=</span><span class="st">&quot;Producción (T/acre)&quot;</span>, <span class="at">color=</span><span class="st">&quot;Variedad&quot;</span>, <span class="at">shape=</span><span class="st">&quot;Bloques&quot;</span>)</span></code></pre></div>
<p><img src="PractCasa05-full_files/figure-html/unnamed-chunk-9-1.png" /><!-- --></p>
</div>
</div>
<div id="ejercicio-2" class="section level1">
<h1><strong>Ejercicio 2:</strong></h1>
<p>Carga la base de datos <code>ergoStool</code> de la librería <code>nlme</code>.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(&quot;nlme&quot;)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;nlme&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:lme4&#39;:
## 
##     lmList</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     collapse</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(ergoStool)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ergoStool)</span></code></pre></div>
<pre><code>## Grouped Data: effort ~ Type | Subject
##   effort Type Subject
## 1     12   T1       1
## 2     15   T2       1
## 3     12   T3       1
## 4     10   T4       1
## 5     10   T1       2
## 6     14   T2       2</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ergoStool)</span></code></pre></div>
<pre><code>## Classes &#39;nffGroupedData&#39;, &#39;nfGroupedData&#39;, &#39;groupedData&#39; and &#39;data.frame&#39;:   36 obs. of  3 variables:
##  $ effort : num  12 15 12 10 10 14 13 12 7 14 ...
##  $ Type   : Factor w/ 4 levels &quot;T1&quot;,&quot;T2&quot;,&quot;T3&quot;,..: 1 2 3 4 1 2 3 4 1 2 ...
##  $ Subject: Ord.factor w/ 9 levels &quot;8&quot;&lt;&quot;5&quot;&lt;&quot;4&quot;&lt;&quot;9&quot;&lt;..: 8 8 8 8 9 9 9 9 6 6 ...
##  - attr(*, &quot;formula&quot;)=Class &#39;formula&#39;  language effort ~ Type | Subject
##   .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt; 
##  - attr(*, &quot;labels&quot;)=List of 2
##   ..$ x: chr &quot;Type of stool&quot;
##   ..$ y: chr &quot;Effort required to arise&quot;
##  - attr(*, &quot;units&quot;)=List of 1
##   ..$ y: chr &quot;(Borg scale)&quot;
##  - attr(*, &quot;FUN&quot;)=function (x)  
##   ..- attr(*, &quot;source&quot;)= chr &quot;function (x) mean(x, na.rm = TRUE)&quot;
##  - attr(*, &quot;order.groups&quot;)= logi TRUE</code></pre>
<p>El estudio se generó con un muestreo con repeticiones (columna <code>Subject</code>) para explicar el esfuerzo <code>effort</code> definido por tipos <code>Type</code>. Realiza un modelo tomando en cuenta a <code>Subject</code> como efecto aleatorio.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ver Posible efecto aleatorio de Subject</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(effort <span class="sc">~</span> Type, <span class="at">data =</span> ergoStool)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>resid2 <span class="ot">&lt;-</span> <span class="fu">residuals</span>(lm2)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(resid2 <span class="sc">~</span> ergoStool<span class="sc">$</span>Subject)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">0</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="PractCasa05-full_files/figure-html/unnamed-chunk-11-1.png" /><!-- --></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar el único modelo posible con Subject como intercepto aleatorio </span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co"># effort como variable respuesta y Type como variable explicativa</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(effort <span class="sc">~</span> Type <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>Subject), <span class="at">data =</span> ergoStool, <span class="at">REML=</span><span class="cn">TRUE</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: effort ~ Type + (1 | Subject)
##    Data: ergoStool
## 
## REML criterion at convergence: 121.1
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.80200 -0.64317  0.05783  0.70100  1.63142 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Subject  (Intercept) 1.775    1.332   
##  Residual             1.211    1.100   
## Number of obs: 36, groups:  Subject, 9
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   8.5556     0.5760  14.853
## TypeT2        3.8889     0.5187   7.498
## TypeT3        2.2222     0.5187   4.284
## TypeT4        0.6667     0.5187   1.285
## 
## Correlation of Fixed Effects:
##        (Intr) TypeT2 TypeT3
## TypeT2 -0.450              
## TypeT3 -0.450  0.500       
## TypeT4 -0.450  0.500  0.500</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Realiza el modelo con intercepto nulo para que se muestren todas las categorías</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(effort <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> Type <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>Subject), <span class="at">data =</span> ergoStool, <span class="at">REML=</span><span class="cn">TRUE</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: effort ~ 0 + Type + (1 | Subject)
##    Data: ergoStool
## 
## REML criterion at convergence: 121.1
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.80200 -0.64317  0.05783  0.70100  1.63142 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Subject  (Intercept) 1.775    1.332   
##  Residual             1.211    1.100   
## Number of obs: 36, groups:  Subject, 9
## 
## Fixed effects:
##        Estimate Std. Error t value
## TypeT1    8.556      0.576   14.85
## TypeT2   12.444      0.576   21.60
## TypeT3   10.778      0.576   18.71
## TypeT4    9.222      0.576   16.01
## 
## Correlation of Fixed Effects:
##        TypeT1 TypeT2 TypeT3
## TypeT2 0.595               
## TypeT3 0.595  0.595        
## TypeT4 0.595  0.595  0.595</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Revisar el gráfico de gusano para verificar el efecto aleatorio</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot</span>(<span class="fu">ranef</span>(m2, <span class="at">condVar=</span><span class="cn">TRUE</span>), <span class="at">strip=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## $Subject</code></pre>
<p><img src="PractCasa05-full_files/figure-html/unnamed-chunk-11-2.png" /><!-- --></p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico de efectos fijos o predictivo</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m2, <span class="at">type=</span><span class="st">&quot;eff&quot;</span>)</span></code></pre></div>
<pre><code>## $Type</code></pre>
<p><img src="PractCasa05-full_files/figure-html/unnamed-chunk-11-3.png" /><!-- --></p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener los coeficientes para ambos efectos aleatorios B y V anidado en B</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Verifica aquí si es que los efectos fijos son significativos revisando que </span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co"># los intervalos de confianza bajo (low) y alto (high) no incluyen al cero </span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>coef.B2 <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(broom.mixed<span class="sc">::</span><span class="fu">tidy</span>(m2, <span class="at">conf.int=</span><span class="cn">TRUE</span>))[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,]</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>coef.B2</span></code></pre></div>
<pre><code>##   effect group   term  estimate std.error statistic  conf.low conf.high
## 1  fixed  &lt;NA&gt; TypeT1  8.555556 0.5760123  14.85308  7.426592  9.684519
## 2  fixed  &lt;NA&gt; TypeT2 12.444444 0.5760123  21.60448 11.315481 13.573408
## 3  fixed  &lt;NA&gt; TypeT3 10.777778 0.5760123  18.71102  9.648814 11.906741
## 4  fixed  &lt;NA&gt; TypeT4  9.222222 0.5760123  16.01046  8.093259 10.351186</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reemplaza los valores de la columna term por las etiquetas reales de la</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co"># variable Type en ergoStol</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>coef.B2<span class="sc">$</span>term <span class="ot">&lt;-</span> <span class="fu">unique</span>(ergoStool<span class="sc">$</span>Type)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>coef.B2</span></code></pre></div>
<pre><code>##   effect group term  estimate std.error statistic  conf.low conf.high
## 1  fixed  &lt;NA&gt;   T1  8.555556 0.5760123  14.85308  7.426592  9.684519
## 2  fixed  &lt;NA&gt;   T2 12.444444 0.5760123  21.60448 11.315481 13.573408
## 3  fixed  &lt;NA&gt;   T3 10.777778 0.5760123  18.71102  9.648814 11.906741
## 4  fixed  &lt;NA&gt;   T4  9.222222 0.5760123  16.01046  8.093259 10.351186</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generar el gráfico</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data=</span>ergoStool, <span class="fu">aes</span>(<span class="at">x=</span>Type, <span class="at">y=</span>effort, <span class="at">color=</span>Type), <span class="at">width=</span><span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>coef.B2, <span class="fu">aes</span>(<span class="at">x=</span>term, <span class="at">y=</span>estimate), <span class="at">shape=</span><span class="dv">15</span>)<span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data=</span>coef.B2, <span class="fu">aes</span>(<span class="at">x=</span>term, <span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high), </span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;LMM del Esfuerzo vs el Tipo&quot;</span>, </span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle=</span><span class="st">&quot;Modelo con efectos aleatorios definidos por Subject&quot;</span>,  </span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">&quot;Tipo&quot;</span>, <span class="at">y=</span><span class="st">&quot;Esfuerzo&quot;</span>, <span class="at">color=</span><span class="st">&quot;Tipo&quot;</span>)</span></code></pre></div>
<p><img src="PractCasa05-full_files/figure-html/unnamed-chunk-11-4.png" /><!-- --></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
