<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Análisis Estadístico Básico con R</title>

<script src="site_libs/header-attrs-2.7.3/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">IrwingRLab</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Inicio</a>
</li>
<li>
  <a href="PractCasa01-full.html">Practica de Casa 1</a>
</li>
<li>
  <a href="PractCasa02-full.html">Practica de Casa 2</a>
</li>
<li>
  <a href="PractCasa03-full.html">Practica de Casa 3</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Análisis Estadístico Básico con R</h1>

</div>

<div id="TOC">
yes
</div>

<div id="práctica-de-casa-03---análisis-estadístico-básico-i" class="section level1">
<h1><strong>Práctica de Casa 03 - Análisis Estadístico Básico I</strong></h1>
<p>Last compiled: 2021-03-12</p>
<p>Link de la práctica desarrollada: <a href="https://irwingss.github.io/IrwingRLab/PractCasa03-full.html">Práctica de Casa 03 - Análisis Estadístico Básico I (irwingss.github.io)</a></p>
<p>Realiza los siguientes ejercicios durante tu tiempo libre para reforzar la información sobre análisis estadístico que hemos aprendido entre las semanas 4 y 5 del programa (Curso 2).</p>
<p>Recuerda realizar esta práctica luego de haber desarrollado:</p>
<ul>
<li><p>R-Notebook-C2-S1.Rmd</p></li>
<li><p>R-Notebook-C2-S2.Rmd</p></li>
</ul>
<blockquote>
<p><strong>Nota 1:</strong> Si necesitas crear un code chunk los atajos en el teclado son en WINDOWS: <code>Crtl+Alt+i</code>, y en MAC: <code>Command+Alt+i</code>.</p>
<p><strong>Nota 2:</strong> Deberás descargar los archivos excel del Campus Virtual de Instituto de Ciencias Antonio Brack para que los cargues a R y puedas desarrollar los ejercicios. Para poder cargarlos ejecutándo el código que te dejamos en cada ejercicio, debes verificar que pegaste los archivos excel en el directorio de trabajo actual de tu RStudio, el cual puedes conocer si ejecutas:</p>
</blockquote>
<pre class="r"><code>getwd()</code></pre>
<p>Activa las librarías a usar</p>
<pre class="r"><code>library(tidyverse)
library(moments)
library(nortest)
library(rstatix)
library(broom)
library(pwr)</code></pre>
</div>
<div id="ejercicio-1-comparaciones-de-una-muestra" class="section level1">
<h1><strong>Ejercicio 1: Comparaciones de una muestra</strong></h1>
<p>Se tiene un conjunto de datos de pesos de una muestra de ratones. Se quiere conocer si el promedio de peso del grupo de ratones es significativamente:</p>
<ol style="list-style-type: decimal">
<li><p>diferente de 26 gr.,</p></li>
<li><p>mayor a 26 gr.,</p></li>
<li><p>menor a 26 gr.</p></li>
</ol>
<p>Debes, por lo tanto, realizar tres test de comparación de grupos. Antes de realizar los análisis, deberás comprobar normalidad del conjunto de datos de peso utilizando todas las técnicas aprendidas en clase.</p>
<p>Carga el excel <code>data_ratones.xlsx</code> y asígnale el nombre <code>ratones</code>.</p>
<p>Desarrolla lo siguiente:</p>
<pre class="r"><code># Carga el excel data_ratones.xlsx y asígnale el nombre ratones.
ratones &lt;- openxlsx::read.xlsx(&quot;~\\Proyectos_R\\2021\\R Data Science\\C2-S2\\data_ratones.xlsx&quot;)

# Realiza un boxplot y gráfico de densidad para 
# explorar cómo luce la distribución de los datos.
# Trata de analizar la curva y predecir si habría 
# normalidad en los datos:
# Boxplot:
boxplot(ratones$peso)</code></pre>
<p><img src="PractCasa03-full_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code># Gráfico de Densidad:
plot(density(ratones$peso), main = &quot;Peso ratones&quot;)</code></pre>
<p><img src="PractCasa03-full_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<pre class="r"><code># Ejecuta un test de normalidad con los datos:
shapiro.test(ratones$peso)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  ratones$peso
## W = 0.9526, p-value = 0.6993</code></pre>
<pre class="r"><code># Verifica la simetría y curtosis del conjunto de datos:
library(moments)
skewness(ratones$peso)</code></pre>
<pre><code>## [1] -0.4288947</code></pre>
<pre class="r"><code>kurtosis(ratones$peso)</code></pre>
<pre><code>## [1] 2.669256</code></pre>
<pre class="r"><code># Crea un gráfico Q-Q Plot
qqnorm(ratones$peso)
qqline(ratones$peso)</code></pre>
<p><img src="PractCasa03-full_files/figure-html/unnamed-chunk-3-3.png" width="672" /></p>
<p><strong>Sección de aprendizaje</strong><br />
Ahora aprenderás a realizar un Q-Q Plot más rápido con la función qqPlot() de la libraría car. Instala la librería car desde el panel Packages/Install o ejecutándo el siguiente código:</p>
<pre class="r"><code>install.packages(&quot;car&quot;)</code></pre>
<pre class="r"><code># Activa la librería car
library(car)

# Crea el qqPlot() de la base de datos ratones$peso
qqPlot(ratones$peso)</code></pre>
<p><img src="PractCasa03-full_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre><code>## [1] 4 3</code></pre>
<p><strong>Continua con el Ejercicio 1:</strong></p>
<pre class="r"><code># Test 1: Averigua si el promedio de peso de los ratones evaluados
# difiere significativamente de 25 gr (prueba de dos colas)
t.test(ratones$peso, mu = 26, alternative = &quot;two.sided&quot;)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  ratones$peso
## t = -10.657, df = 9, p-value = 2.102e-06
## alternative hypothesis: true mean is not equal to 26
## 95 percent confidence interval:
##  17.8172 20.6828
## sample estimates:
## mean of x 
##     19.25</code></pre>
<pre class="r"><code># Test 2: Averigua si el promedio de peso de los ratones evaluados
# es significativamente menor que 25 gr (prueba de una colas)
t.test(ratones$peso, mu = 26, alternative = &quot;less&quot;)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  ratones$peso
## t = -10.657, df = 9, p-value = 1.051e-06
## alternative hypothesis: true mean is less than 26
## 95 percent confidence interval:
##      -Inf 20.41105
## sample estimates:
## mean of x 
##     19.25</code></pre>
<pre class="r"><code># Test 3: Averigua si el promedio de peso de los ratones evaluados
# es significativamente mayor que 25 gr (prueba de una colas)
t.test(ratones$peso, mu = 26, alternative = &quot;greater&quot;)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  ratones$peso
## t = -10.657, df = 9, p-value = 1
## alternative hypothesis: true mean is greater than 26
## 95 percent confidence interval:
##  18.08895      Inf
## sample estimates:
## mean of x 
##     19.25</code></pre>
</div>
<div id="ejercicio-2-comparaciones-de-dos-muestras" class="section level1">
<h1><strong>Ejercicio 2: Comparaciones de dos muestras</strong></h1>
<p>En un estudio, se han evaluado el efecto de 2 drogas (Columna <code>Droga</code>, valores A y B) en 8 pacientes y se pretende conocer:</p>
<ol style="list-style-type: decimal">
<li><p>si existen diferencias significativas entre el conjunto de datos de la droga A y el conjunto de la droga B.</p></li>
<li><p>si el promedio del grupo A es significativamente mayor al promedio del grupo B.</p></li>
<li><p>si el promedio del grupo A es significativamente menor al promedio del grupo B.</p></li>
</ol>
<p>Debes realizar tres test de T. Da un vistazo a los datos para decidir cual test debes realizar en base a la independencia de los datos o diferencia de varianza.</p>
<p>Carga el excel <code>glicolipido.xlsx</code> y asígnale el nombre <code>glico</code>.</p>
<p>Desarrolla lo siguiente:</p>
<pre class="r"><code># Carga el excel glicolipido.xlsx y asígnale el nombre glico.
glico &lt;- openxlsx::read.xlsx(&quot;~\\Proyectos_R\\2021\\R Data Science\\C2-S2\\glicolipido.xlsx&quot;)

# Realiza el boxplot para cada droga
boxplot(Glicolipido~Droga, data=glico)</code></pre>
<p><img src="PractCasa03-full_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code># Test 1: averigua si existen diferencias significativas entre el conjunto de datos de la droga A y el conjunto de la droga B
t.test(Glicolipido ~ Droga, data = glico, paired = TRUE)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  Glicolipido by Droga
## t = 5.9368, df = 7, p-value = 0.0005777
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   6.904491 16.045509
## sample estimates:
## mean of the differences 
##                  11.475</code></pre>
<pre class="r"><code># Test 2: averigua si el promedio del grupo A es significativamente mayor al promedio del grupo B
t.test(Glicolipido ~ Droga, data = glico, 
       paired = TRUE, alternative = &quot;greater&quot;)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  Glicolipido by Droga
## t = 5.9368, df = 7, p-value = 0.0002888
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  7.813028      Inf
## sample estimates:
## mean of the differences 
##                  11.475</code></pre>
<pre class="r"><code># Test 3: averigua si el promedio del grupo A es significativamente menor al promedio del grupo B.
t.test(Glicolipido ~ Droga, data = glico, 
       paired = TRUE, alternative = &quot;less&quot;)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  Glicolipido by Droga
## t = 5.9368, df = 7, p-value = 0.9997
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##      -Inf 15.13697
## sample estimates:
## mean of the differences 
##                  11.475</code></pre>
</div>
<div id="ejercicio-3-comparaciones-de-dos-muestras" class="section level1">
<h1><strong>Ejercicio 3: Comparaciones de dos muestras</strong></h1>
<p>Siguiendo con la misma base de datos anterior, verifica si existen diferencias estadísticas entre los sexos para la medición de glicolipido (columna Glicolipido). Comprueba:</p>
<ol style="list-style-type: decimal">
<li><p>si existen diferencias significativas entre el conjunto de datos sexo Hombre y el conjunto sexo Mujer.</p></li>
<li><p>si el promedio del sexo Hombre es significativamente mayor al promedio del sexo Mujer.</p></li>
<li><p>si el promedio del sexo Hombre es significativamente menor al promedio del sexo Mujer.</p></li>
</ol>
<p>Debes realizar tres test de T. Da un vistazo a los datos para decidir cual test debes realizar en base a la independencia de los datos o diferencia de varianza.</p>
<pre class="r"><code># Test 1: averigua si existen diferencias significativas entre el conjunto sexo Hombre y el conjunto sexo Mujer
t.test(Glicolipido ~ Sexo, data = glico, paired = TRUE)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  Glicolipido by Sexo
## t = -0.67495, df = 7, p-value = 0.5214
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.139111  1.189111
## sample estimates:
## mean of the differences 
##                  -0.475</code></pre>
<pre class="r"><code># Test 2: averigua si el promedio del sexo Hombre es significativamente mayor al promedio del sexo Mujer
t.test(Glicolipido ~ Sexo, data = glico, 
       paired = TRUE, alternative = &quot;greater&quot;)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  Glicolipido by Sexo
## t = -0.67495, df = 7, p-value = 0.7393
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  -1.808315       Inf
## sample estimates:
## mean of the differences 
##                  -0.475</code></pre>
<pre class="r"><code># Test 3: averigua si el promedio del sexo Hombre es significativamente menor al promedio del sexo Mujer
t.test(Glicolipido ~ Sexo, data = glico, 
       paired = TRUE, alternative = &quot;less&quot;)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  Glicolipido by Sexo
## t = -0.67495, df = 7, p-value = 0.2607
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##       -Inf 0.8583148
## sample estimates:
## mean of the differences 
##                  -0.475</code></pre>
</div>
<div id="ejercicio-4-lm" class="section level1">
<h1><strong>Ejercicio 4: LM</strong></h1>
<p>Un estudio de la microbiota del suelo de una región trató de averiguar cuánto varía la concentración de nitrógeno disponible en el suelo (columna <code>conc.N</code>) en relación a la cantidad de colonias de bacterias nitrificantes (columna <code>colonias</code>) halladas en las muestras obtenidas de la siembra estandarizada en placas petri.</p>
<p>Carga el excel <code>suelos.xlsx</code> y asígnale el nombre <code>suelos</code>.</p>
<div id="parte-1-modelos-lineales-simples" class="section level3">
<h3><strong>Parte 1: Modelos lineales simples</strong></h3>
<p>Desarrolla lo siguiente:</p>
<pre class="r"><code># Carga el excel suelos.xlsx y asígnale el nombre suelos.
suelos &lt;-  openxlsx::read.xlsx(&quot;~\\Proyectos_R\\2021\\R Data Science\\C2-S2\\suelos.xlsx&quot;)

# Búsqueda de outliers con boxplot
boxplot(suelos$conc.N)</code></pre>
<p><img src="PractCasa03-full_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>boxplot.stats(suelos$conc.N)$out</code></pre>
<pre><code>## [1] 70 50</code></pre>
<pre class="r"><code># Eliminación de outliers
outliers  &lt;- identify_outliers(suelos, conc.N)
sinOutliers &lt;- anti_join(suelos, outliers) </code></pre>
<pre><code>## Joining, by = c(&quot;conc.N&quot;, &quot;colonias&quot;, &quot;plant.simbio&quot;, &quot;div.esp.descomp&quot;)</code></pre>
<pre class="r"><code># Verificando que suelos ya no contiene outliers
boxplot(sinOutliers$conc.N)</code></pre>
<p><img src="PractCasa03-full_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
<pre class="r"><code># Verifica linearidad de las variables respuesta y explicativa
names(sinOutliers)</code></pre>
<pre><code>## [1] &quot;conc.N&quot;          &quot;colonias&quot;        &quot;plant.simbio&quot;    &quot;div.esp.descomp&quot;</code></pre>
<pre class="r"><code>plot(conc.N~colonias, data=sinOutliers)</code></pre>
<p><img src="PractCasa03-full_files/figure-html/unnamed-chunk-9-3.png" width="672" /></p>
<pre class="r"><code># Realiza el modelo
modelo &lt;- lm(conc.N~colonias, data=sinOutliers)

# Verifica las asunciones teóricas restantes
par(mfrow=c(2,2))
plot(modelo)</code></pre>
<p><img src="PractCasa03-full_files/figure-html/unnamed-chunk-9-4.png" width="672" /></p>
<pre class="r"><code>dev.off() #usa siempre dev.off() luego de par() para evitar que siga activo</code></pre>
<pre><code>## null device 
##           1</code></pre>
<pre class="r"><code># Comprueba la normalidad de los residuales, obtenidos con la función resid()
nortest::ad.test(resid(modelo))</code></pre>
<pre><code>## 
##  Anderson-Darling normality test
## 
## data:  resid(modelo)
## A = 0.49121, p-value = 0.217</code></pre>
<pre class="r"><code>moments::skewness(resid(modelo))</code></pre>
<pre><code>## [1] -0.08863202</code></pre>
<pre class="r"><code>moments::kurtosis(resid(modelo))</code></pre>
<pre><code>## [1] 2.779015</code></pre>
<pre class="r"><code>plot(density(resid(modelo)))

# Obtén los resultados del modelo e interprétalo
summary(modelo)</code></pre>
<pre><code>## 
## Call:
## lm(formula = conc.N ~ colonias, data = sinOutliers)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.0632  -2.3454  -0.2295   2.4805   8.6548 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 8.439112   0.549412   15.36   &lt;2e-16 ***
## colonias    0.047537   0.002691   17.67   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.91 on 198 degrees of freedom
## Multiple R-squared:  0.6119, Adjusted R-squared:  0.6099 
## F-statistic: 312.1 on 1 and 198 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Interpreta los resultados de la regresión y responde:</strong></p>
<p><strong>P1:</strong> <em>¿El modelo fue significativo?</em></p>
<p><strong>Rpta/.</strong> Sí, con p-value: &lt; 2.2e-16, generado a partir de la prueba F con valor 312.1 y 198 grados de libertad.</p>
<p><strong><br />
P2:</strong> <em>¿Cuánto aumenta el nitrógeno en relación a las colonias de bacterias nitrificantes contabilizadas en la muestra?</em></p>
<p><strong>Rpta/.</strong> Por cada colonia contabilizada en la muestra sembrada en placa petri, la concentración del nitrógeno en el suelo aumenta en 0.048 unidades.</p>
<p><strong>P3:</strong> <em>¿Cuánta varianza de la variable respuesta es explicada por la variable respuesta?</em></p>
<p><strong>Rpta/.</strong> 60.99%, debido al Adjusted R-squared: 0.6099</p>
</div>
<div id="parte-2-modelos-lineales-múltiples-aditivos" class="section level3">
<h3><strong>Parte 2: Modelos lineales múltiples (aditivos)</strong></h3>
<p>Considera incluir en el modelo dos nuevas variables explicativas: un indice de diversidad de plantas <code>plant.simbio</code> y la diversidad de especies descomponedoras de materia orgánica <code>div.esp.descomp</code> como potenciales variables que puedan mejorar el modelo. Crea la variable <code>modelo2</code> incluyendo dichas nuevas variables y verifica:</p>
<ol style="list-style-type: decimal">
<li><p>Si <code>modelo2</code> es significativo.</p></li>
<li><p>Si hay variables que no sean significativas (ver columna <code>Pr(&gt;|t|)</code> en el resumen de <code>summary()</code>).</p></li>
</ol>
<pre class="r"><code>names(sinOutliers)</code></pre>
<pre><code>## [1] &quot;conc.N&quot;          &quot;colonias&quot;        &quot;plant.simbio&quot;    &quot;div.esp.descomp&quot;</code></pre>
<pre class="r"><code>modelo2 &lt;- lm(conc.N~colonias+plant.simbio+div.esp.descomp, data=sinOutliers)
modelo2 &lt;- lm(conc.N~.,data=sinOutliers)
summary(modelo2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = conc.N ~ ., data = sinOutliers)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.5161  -1.0677   0.2979   1.4510   3.4013 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      3.565738   0.442005   8.067 7.05e-14 ***
## colonias         0.045751   0.001394  32.824  &lt; 2e-16 ***
## plant.simbio     0.187530   0.008311  22.564  &lt; 2e-16 ***
## div.esp.descomp -0.001294   0.005660  -0.229    0.819    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.023 on 196 degrees of freedom
## Multiple R-squared:  0.8972, Adjusted R-squared:  0.8956 
## F-statistic: 570.3 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>De haber detectado alguna variable explicativa no significativa, esta debe ser eliminada del modelo ya que le no aportan nada. Por el contrario, el modelo se beneficia al eliminar variables no significativas. Crea la variable <code>modelo3</code> que contenga el nuevo modelo mejorado.</p>
<pre class="r"><code>modelo3 &lt;- lm(conc.N~.,data=sinOutliers[,-4])
summary(modelo3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = conc.N ~ ., data = sinOutliers[, -4])
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.5572  -1.0502   0.2906   1.4049   3.3994 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.50532    0.35339   9.919   &lt;2e-16 ***
## colonias      0.04575    0.00139  32.909   &lt;2e-16 ***
## plant.simbio  0.18799    0.00804  23.382   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.018 on 197 degrees of freedom
## Multiple R-squared:  0.8972, Adjusted R-squared:  0.8962 
## F-statistic: 859.6 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>P4:</strong> <em>¿El modelo muestra alguna mejora respecto a la cantidad de varianza explicada por las variables independientes (explicativas)? (comparar R cuadrados ajustados de los modelos 2 y 3)</em></p>
<p><strong>Rpta/.</strong> Sí se mejoró el modelo al incluir a la variable plant.simbio, con un R2 ajustado de 0.89, es decir que las variables explicativas de este modelo explican el 89% de la varianza de la variable respuesta <code>conc.N</code>.</p>
</div>
<div id="parte-3-interpretación-de-coeficientes-en-modelos-simples-o-múltiples-aditivos" class="section level3">
<h3><strong>Parte 3: Interpretación de coeficientes en modelos simples o múltiples aditivos</strong></h3>
<p>En consecuencia, podemos leer un modelo simple y aditivo de la siguiente manera, siendo que la fórmula de una regresión simple es:</p>
<p><span class="math display">\[
y=b0+b1∗x1
\]</span></p>
<p>y la de una regresión múltiple aditiva con dos variables explicativas es:</p>
<p><span class="math display">\[
y=b0+b1∗x1+b2∗x2
\]</span></p>
<p><strong>En ambos casos, los coeficientes se leen igual:</strong></p>
<ul>
<li><p><strong>Intercepto (b0):</strong> es el promedio de la variable respuesta y cuando la o las variables respuesta son 0 (es decir, sin contar con el efecto de la variable explicativa).</p>
<p><span class="math display">\[
y=b0+b1∗(0) = b0+0 = b0  
\]</span></p></li>
</ul>
<p>o para las regresiones múltiples aditivas<span class="math display">\[
y=b0+b1∗(0)+b2∗(0) = b0+0+0 = b0  
\]</span></p>
<ul>
<li><strong>Pendiente de x1 (b1) o x2 (b2):</strong> se interpreta como "el aumento de 1 unidad de la variable explicativa x1, representa un aumento de b1 en el promedio de la variable respuesta y. Lo mismo para x2 y su respectivo aumento b2.</li>
</ul>
</div>
<div id="parte-4-modelos-lineales-múltiples-interacción" class="section level3">
<h3><strong>Parte 4: Modelos lineales múltiples (interacción)</strong></h3>
<p>Este tipo de modelos se desarrollan cuando uno quiere responder preguntas del tipo:</p>
<ol style="list-style-type: decimal">
<li><p>¿La variable C modera la relación entre B y A?,</p></li>
<li><p>¿La fuerza del efecto B y A depende de C?,</p></li>
<li><p>¿Cómo afecta C a la relación entre B y A? ,</p></li>
<li><p>¿Cómo influye C en la relación B y A?</p></li>
</ol>
<p>Ahora, verifica si es que, adicionalmente a los efectos principales individuales de las variables, existe algún efecto significativo de la interacción de las variables respuesta <code>colonias</code> y <code>plant.simbio</code> que explique algo de la varianza restante de la variable respuesta <code>conc.N</code>. Para indicar interacciones debes colocar un símbolo de multiplicación entre las variables que deseas que interactúen en el modelo.</p>
<pre class="r"><code>modelo4 &lt;- lm(conc.N ~ colonias*plant.simbio, data = sinOutliers)
summary(modelo4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = conc.N ~ colonias * plant.simbio, data = sinOutliers)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.6039 -0.4833  0.2197  0.7137  1.8295 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           8.100e+00  2.974e-01  27.233   &lt;2e-16 ***
## colonias              1.910e-02  1.504e-03  12.699   &lt;2e-16 ***
## plant.simbio          2.886e-02  8.905e-03   3.241   0.0014 ** 
## colonias:plant.simbio 9.054e-04  4.368e-05  20.727   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.132 on 196 degrees of freedom
## Multiple R-squared:  0.9678, Adjusted R-squared:  0.9673 
## F-statistic:  1963 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="parte-5-interpretación-de-coeficientes-en-modelos-lineales-múltiples-interacción" class="section level3">
<h3><strong>Parte 5: Interpretación de coeficientes en modelos lineales múltiples (interacción)</strong></h3>
<p>Cuando existe un efecto de interacción, el efecto de una variable explicativa (x1) depende de los valores de una o más variables explicativas (x2, x3,…).</p>
<p>La interacción en un modelo con interacciones cambia el cómo interpretamos los resultados. Primero hay que revisar si la interacción fue significativa. Antes de interpretar, revisemos la fórmula de la regresión múltiple con interacción:<span class="math display">\[
y=b0+b1∗x1+b2∗x2+b3∗x1∗x2
\]</span></p>
<p>Si factorizamos la fórmula tomando en cuenta x1, tenemos:</p>
<p><span class="math display">\[
y=(b0+b2∗x2)+(b1+b3∗x2)∗x1
\]</span></p>
<p>Si nos percatamos, esa fórmula se asemeja en estructura a <span class="math inline">\(y=b0+b1*x1\)</span>, ¿cierto?, significa que de la ecuación anterior, <span class="math inline">\((b1+b3∗x2)\)</span> es la pendiente de x1. Es decir, la pendiente de la variable x1 cambiará por la influencia de la variable x2.</p>
<p>Cuando se realiza una regresión múltiple con interacciones buscamos interpretar el término de la interacción, por lo que no nos interesa demasiado el efecto de cada variable respuesta independientemente una de la otra.</p>
<ul>
<li><u>El efecto de <code>colonias</code>(la primera variable explicativa) es:</u> <span class="math inline">\(b1*x1+ b3*x1*x2\)</span></li>
</ul>
<p>lo que es en nuestro ejemplo: <span class="math inline">\(b1*colonias + b3*colonias*plant.simbio\)</span></p>
<p>Reemplazando los valores de la regresión b1 es 0.04575 y b3 es 0.18799, tenemos: <span class="math inline">\(0.04575*colonias + 0.18799*colonias*plant.simbio\)</span></p>
<p>Para interpretar decimos, si la variable <code>plant.simbio</code> es 0 (el indice de diversidad de plantas simbióticas es 0), entonces <code>conc.N</code> (la variable respuesta <code>y</code>) se reduce a <span class="math inline">\(0.04575*colonias + 0.18799*colonias*0 = 0.04575*colonias\)</span>, es decir, cuando <code>plant.simbio</code> es 0, una unidad de incremento de colonias, aumenta el promedio esperado de la variable <code>conc.N</code> (y) en 0.04575 unidades.</p>
<p>Para interpretar decimos, si la variable <code>plant.simbio</code> es 1 (el indice de diversidad de plantas simbióticas es 0), entonces <code>conc.N</code> (la variable respuesta <code>y</code>) se reduce a <span class="math inline">\(0.04575*colonias + 0.18799*colonias*1 = 0.04575*colonias + 0.18799*colonias\)</span>, es decir, cuando <code>plant.simbio</code> es 1, una unidad de incremento de colonias, incrementa el promedio esperado de la variable <code>conc.N</code> (y) en 0.04575 + 0.18799 unidades, o 0.23374 unidades.</p>
<ul>
<li><p>De la misma manera podrías interpretar el efecto de <code>plant.simbio.</code></p></li>
<li><p><strong>Haciendo una interpretación “más del mundo real”</strong>, podemos decir: la concentración de nitrógeno (<code>conc.N</code>) tiende a ser mayor en zonas donde la cantidad de unidades formadoras de colonias (<code>colonias</code>) es mayor; sin embargo, esta relación se incrementa más cuando los suelos, además de tener mayor abundancia de unidades formadoras de colonias, tiene también mayor diversidad de plantas simbióticas (<code>plant.simbio</code>). En suma, la fuerza de la relación positiva entre <code>conc.N</code> (y) y <code>colonias</code> (x1) depende de la presencia de un mayor valor de <code>plant.simbio</code> (x2) en la zona de estudios.</p></li>
</ul>
<blockquote>
<p><strong>Nota final:</strong> Gracias al principio jerárquico en modelos lineales, si incluimos una interacción en un modelo y es significativa, no importa si p-valores de los efectos independientes no lo son.</p>
</blockquote>
</div>
</div>
<div id="ejercicio-5-anova" class="section level1">
<h1><strong>Ejercicio 5: ANOVA</strong></h1>
<p>Se realizaron mediciones de la longitud total coporal (columna <code>long_total</code>) de tres subespecie de la especie Microlophus thoraccicus, halladas en la costa norte de Peru. Realiza en análisis de varianza ANOVA para corroborar si existen diferencias entre los grupos. De hallar diferencias, identifica el grupo que es diferente entre los tres. Carga el excel sp.xlsx para realizar este ejercicio.</p>
<pre class="r"><code># Carga el excel sp.xlsx y asígnale el nombre sp
sp &lt;- openxlsx::read.xlsx(&quot;~\\Proyectos_R\\2021\\R Data Science\\C2-S2\\sp.xlsx&quot;)

# Elimina outliers
out &lt;- sp %&gt;% 
  group_by(ssp) %&gt;% 
  identify_outliers(long_total)

sp2 &lt;- anti_join(sp,out)

# Con la base de datos filtrada, si es que fue necesario,
# analiza qué anova realizarás. Comprueba si se debe 
# realizar un anova balanceado o no balanceado.
table(sp$ssp)

# Realiza el modelo lineal y asignalo con le nombre &quot;modelo&quot;
modelo  &lt;- lm(long_total ~ ssp, data = sp)

# Realiza el ANOVA
anova(modelo) 

# Verifica la normalidad de los residuales
shapiro.test(resid(modelo))

# Verifica la homogeneidad de varianzas
bartlett.test(long_total ~ ssp, data = sp)

# Realiza el Test posthoc respectivo
TukeyHSD(aov(modelo))</code></pre>
</div>
<div id="ejercicio-6-balancear-un-anova-una-vía" class="section level1">
<h1><strong>Ejercicio 6: Balancear un ANOVA (una vía)</strong></h1>
<p>Muchas veces tenemos N muestral suficiente como para uniformizar el ANOVA. Esta decisión, puede explotar lo mejor del ANOVA balanceado frente a uno desbalanceado. En general, se asume que los ANOVA balanceados tienen un mayor poder estadístico, menor susceptibilidad ante ligeras desviaciones del supuesto de homocedasticidad (igualdad) de varianzas entre grupos, que lo ANOVA no balanceados. Así que este procedimiento te ayudará ante aquellas situaciones en las que necesites balancear.</p>
<p>En el siguiente ejemplo verificaremos si existe diferencias significativas entre los niveles de la variable explicativa <code>tratamiento</code>, respecto a la variable respuesta <code>y</code>. Los niveles de la variable explicativa son 3: Ctrl, trat1 y trat2. Esta base de datos es desbalanceada. Verifica la presencia de outliers y elimínalos. Posteriormente, trata de balancear el análisis, eliminando aleatoriamente filas dentro de los niveles que lo requieran para que todos tengan la misma cantidad de observaciones. Continua verificando los supuestos teóricos del ANOVA balanceado y obtén los resultados. Si el ejercicio lo requiere, realiza un test post hoc para identificar qué nivel de <code>tratamiento</code> es el que genera un mayor incremento en el promedio estimado de la variable <code>y</code>.</p>
<p>Carga el excel <code>ejercicio_grupos.xlsx</code>para comenzar el ejercicio.</p>
<pre class="r"><code># Carga el excel ejercicio_grupos.xlsx y asígnale el nombre grupos
grupos &lt;- openxlsx::read.xlsx(&quot;~\\Proyectos_R\\2021\\R Data Science\\C2-S2\\ejercicio_grupos.xlsx&quot;)

# Genera un boxplot para verificar si hay outliers 
# en la variable respuesta y dentro de cada nivel 
# de la variable tratamiento.
boxplot(grupos$y ~ grupos$tratamiento)</code></pre>
<p><img src="PractCasa03-full_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre class="r"><code># Obten los outliers para cada grupo
# con identify_outliers()
outs &lt;- grupos %&gt;% 
  group_by(tratamiento) %&gt;% 
  identify_outliers(y)

# A2: Elimina los outliers y asigna la tabla limpia con el
# nombre gruposLimpio
gruposLimpio &lt;- anti_join(grupos, outs)</code></pre>
<pre><code>## Joining, by = c(&quot;y&quot;, &quot;x1&quot;, &quot;x2&quot;, &quot;grp&quot;, &quot;tratamiento&quot;)</code></pre>
<pre class="r"><code># Verifica si los niveles de tratamiento están balanceados
table(gruposLimpio$tratamiento)</code></pre>
<pre><code>## 
##  Ctrl trat1 trat2 
##    32    29    30</code></pre>
<p>Balancea el estudio:</p>
<pre class="r"><code># Selecciona de manera aleatoria las observaciones (filas)
# que debes eliminar de gruposLimpio para cada nivel de 
# tratamiento y así balancear el ANOVA
set.seed(12345)
rCtrl &lt;- gruposLimpio %&gt;% filter(tratamiento==&quot;Ctrl&quot;) %&gt;% sample_n(3)
rtrat2 &lt;- gruposLimpio %&gt;% filter(tratamiento==&quot;trat2&quot;) %&gt;% sample_n(1)

# Asigna la base de datos balanceada con el nombre gruposFinal
gruposFinal &lt;- anti_join(gruposLimpio,rCtrl) %&gt;% anti_join(.,rtrat2)</code></pre>
<pre><code>## Joining, by = c(&quot;y&quot;, &quot;x1&quot;, &quot;x2&quot;, &quot;grp&quot;, &quot;tratamiento&quot;)
## Joining, by = c(&quot;y&quot;, &quot;x1&quot;, &quot;x2&quot;, &quot;grp&quot;, &quot;tratamiento&quot;)</code></pre>
<pre class="r"><code># Verifica si realmente está balanceado el ANOVA ahora
table(gruposFinal$tratamiento)</code></pre>
<pre><code>## 
##  Ctrl trat1 trat2 
##    29    29    29</code></pre>
<p>Verifica los supuestos teóricos restantes</p>
<pre class="r"><code># Realiza el modelamiento lineal
mod1 &lt;- lm(y ~ tratamiento, data=gruposFinal)

# A3: Verifica la normalidad de los residuales
shapiro.test(resid(mod1))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resid(mod1)
## W = 0.9906, p-value = 0.7915</code></pre>
<pre class="r"><code>nortest::ad.test(resid(mod1))</code></pre>
<pre><code>## 
##  Anderson-Darling normality test
## 
## data:  resid(mod1)
## A = 0.19844, p-value = 0.8838</code></pre>
<pre class="r"><code># A4: Verifica la homogeneidad de varianzas
bartlett.test(y ~ tratamiento, data=gruposFinal)</code></pre>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  y by tratamiento
## Bartlett&#39;s K-squared = 2.2933, df = 2, p-value = 0.3177</code></pre>
<p>Realiza el ANOVA final y su respectivo post hoc si es necesario</p>
<pre class="r"><code># Modelo final 
anova(mod1)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: y
##             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## tratamiento  2 111.94  55.968  7.7188 0.0008368 ***
## Residuals   84 609.07   7.251                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code># Post Hoc
TukeyHSD(aov(mod1))</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = mod1)
## 
## $tratamiento
##                 diff        lwr      upr     p adj
## trat1-Ctrl  1.258966 -0.4282642 2.946195 0.1824074
## trat2-Ctrl  2.774483  1.0872530 4.461712 0.0005173
## trat2-trat1 1.515517 -0.1717125 3.202747 0.0873564</code></pre>
<p><strong>P1:</strong> <em>¿Existen diferencias significativas entre los grupos?</em></p>
<p><strong>Rpta/.</strong> el Pr(&gt;F) de la variable tratamiento en el resultado del ANOVA es significativo: 0.0008368 ***</p>
<p><strong>P2:</strong> <em>¿Cuál es el tratamiento que generó un mayor incremento del promedio de la variable y?</em></p>
<p><strong>Rpta/.</strong> Al ver el resultado del post hoc, lo primero que se debe revisar es la significancia de las diferencias entre los tratamientos. Las diferencias entre niveles que no son significativos nos indican que no hay evidencia estadística que soporte que dichas restas son diferentes de cero. Por lo que no se puede decir que hay diferencias estadísticas entre los niveles en cuestión. Eso sucede con las restas entre los promedios de <code>trat1-Ctrl</code> y <code>trat2-trat1</code>. Por lo que la única resta de promedios significativa fue <code>trat2-Ctrl</code>= 2.77 (p-valor 0.0005). Interpretando, decimos que: <code>trat2</code> genera un promedio mayor a <code>Ctrl</code>, debido a que la resta de ambos es positiva. Por el contrario, no hay evidencia de que existan diferencias entre <code>trat1-Ctrl</code> y <code>trat2-trat1</code>. En consecuencia, <code>trat2</code> es el tratamiento que genera un mayor incremento de <code>y</code>.</p>
</div>
<div id="ejercicio-7-poder-de-análisis" class="section level1">
<h1><strong>Ejercicio 7: Poder de análisis</strong></h1>
<p>Conocer el poder de un análisis nos puede ayudar a decidir si podemos incrementar el n muestral para obtener un resultado mucho más fiable, estadísticamente hablando.</p>
<p>Desarrolla lo siguiente:</p>
<pre class="r"><code># Calcula el tamaño del efecto del ANOVA balanceado
# qaue desarrollaste anteriormente (redondea el valor a dos decimales)
rstatix::eta_squared(anova(mod1)) %&gt;% round(2)</code></pre>
<pre><code>## tratamiento 
##        0.16</code></pre>
<pre class="r"><code># Calcula el poder del análisis de dicho ANOVA
pwr.anova.test(k=3, sig.level = 0.05, f = 0.13, n=29)</code></pre>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##               k = 3
##               n = 29
##               f = 0.13
##       sig.level = 0.05
##           power = 0.1708106
## 
## NOTE: n is number in each group</code></pre>
<pre class="r"><code># Identifica cuál sería el n muestral necesario para obtener
# un poder de análisis de 80%
pwr.anova.test(k=3, sig.level = 0.05, f = 0.16, power = 0.8)</code></pre>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##               k = 3
##               n = 126.4556
##               f = 0.16
##       sig.level = 0.05
##           power = 0.8
## 
## NOTE: n is number in each group</code></pre>
</div>
<div id="ejercicio-8-anova-no-balanceado-una-vía" class="section level1">
<h1><strong>Ejercicio 8: ANOVA No Balanceado (una vía)</strong></h1>
<p>Trabajemos el ANOVA no balanceado del <strong>Ejercicio 6</strong> y veamos qué diferencias encontramos con los resultados del ANOVA balanceado. Como aquí no necesitamos utilizar los niveles de <code>tratamiento</code> con el mismo n muestral, usaremos la variable creada en el ambiente de R llamada <code>gruposLimpio</code>.</p>
<pre class="r"><code># Realiza el modelamiento lineal
mod2 &lt;- lm(y ~ tratamiento, data=gruposLimpio)

# A3: Verifica la normalidad de los residuales
shapiro.test(resid(mod2))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resid(mod2)
## W = 0.99076, p-value = 0.7795</code></pre>
<pre class="r"><code>nortest::ad.test(resid(mod2))</code></pre>
<pre><code>## 
##  Anderson-Darling normality test
## 
## data:  resid(mod2)
## A = 0.20766, p-value = 0.8625</code></pre>
<pre class="r"><code># A4: Verifica la homogeneidad de varianzas
bartlett.test(y ~ tratamiento, data=gruposLimpio)</code></pre>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  y by tratamiento
## Bartlett&#39;s K-squared = 2.1026, df = 2, p-value = 0.3495</code></pre>
<pre class="r"><code># Modelo final 
anova(mod2)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: y
##             Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## tratamiento  2 105.97  52.985   7.237 0.001231 **
## Residuals   88 644.28   7.321                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code># Post Hoc
TukeyHSD(aov(mod2))</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = mod2)
## 
## $tratamiento
##                 diff         lwr      upr     p adj
## trat1-Ctrl  1.006185 -0.64766568 2.660036 0.3198435
## trat2-Ctrl  2.600542  0.96121431 4.239869 0.0008204
## trat2-trat1 1.594356 -0.08549883 3.274211 0.0665400</code></pre>
<p>En estos casos de anovas de una vía, balanceados o no, el algoritmo de la función <code>anova()</code> es lo suficientemente robusto para mantener los resultados entre ambos. Esto no es igual para ANOVAs de dos vías.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
